### ISSUE TITLE
1x1.png URL change

### ISSUE THREAD

**Issue by osaris** [ianrogren/jquery-backDetect#1]
Correct me If I'm wrong but the 1x1.png file URL used in the `<iframe>` is hardcoded and can't be personnalized with `frameDataSrc`  ?

https://github.com/ianrogren/jquery-backDetect/blob/7b39235719338e05339f2e097005864de82dc208/jquery.backDetect.js#L35

Thanks !

**Comment by ianrogren** [comment]
A little late to respond here, but I just pushed an update where I've made the frameDataSrc an inline image encoded in base 64 which means that the 1x1.png image is no longer needed at this point.
